apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "post.fullname" .) }}
  labels:
    {{- include "post.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "post.selectorLabels" . | nindent 4 }}