apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "notification-service.fullname" .) }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "notification-service.selectorLabels" . | nindent 4 }}