replicaCount: 2

# Image configuration
image:
  repository: <your-acr-name>.azurecr.io/todo-service
  tag: v1.2
  pullPolicy: IfNotPresent

# Image pull secrets for ACR
imagePullSecrets:
  - name: acr-secret

# Service configuration
service:
  type: ClusterIP
  port: 80
  annotations: {}

# Resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Azure Key Vault CSI configuration
azureKeyVault:
  enabled: true
  tenantId: "<your-tenant-id>"
  keyvaultName: "kv-k8s-todo-app"
  useManagedIdentity: true
  userAssignedIdentityID: "<managed-identity-client-id>"

# PostgreSQL configuration (non-secret values)
# postgres:
  # host: "your-postgres-server.postgres.database.azure.com"  # Azure Database for PostgreSQL
  # port: 5432
  # database: tododb
  # sslMode: require  # Required for Azure PostgreSQL

# Health checks
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Network Policy
networkPolicy:
  enabled: true
  allowFrom:
    - podSelector:
        matchLabels:
          app: gateway-service