apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-service.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "gateway-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gateway-service.name" . }}
    spec:
      containers:
        - name: gateway-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080"
          resources:
{{ toYaml .Values.resources | indent 12 }}
