apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-service.fullname" . }}-config
data:
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
