apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "todo-service.name" . }}
    spec:
      containers:
      - name: todo-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:80"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "todo-service.fullname" . }}-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "todo-service.fullname" . }}-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ include "todo-service.fullname" . }}-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "todo-service.fullname" . }}-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "todo-service.fullname" . }}-secret
              key: POSTGRES_PASSWORD
        resources:
{{ toYaml .Values.resources | indent 10 }}
