{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "todo-service.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "todo-service.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- range .Values.networkPolicy.allowFrom }}
  - from:
    - podSelector:
        matchLabels:
          {{- toYaml . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 80
  {{- end }}
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 443   # HTTPS for Azure services
    - protocol: TCP
      port: 53    # DNS
    - protocol: UDP
      port: 53    # DNS
{{- end }}