apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-service.fullname" . }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
