{{- if .Values.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "todo-service.fullname" . }}-spc
spec:
  provider: azure
  secretObjects:
  - secretName: {{ include "todo-service.fullname" . }}-db-secret
    type: Opaque
    data:
    - objectName: postgres-username
      key: username
    - objectName: postgres-password
      key: password
    - objectName: postgres-connection-string-prod
      key: connectionString
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "{{ .Values.azureKeyVault.useManagedIdentity }}"
    userAssignedIdentityID: "{{ .Values.azureKeyVault.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.azureKeyVault.keyvaultName }}"
    tenantId: "{{ .Values.azureKeyVault.tenantId }}"
    objects: |
      array:
        - |
          objectName: postgres-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-connection-string-prod
          objectType: secret
          objectVersion: ""
{{- end }}