{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-service.fullname" . }}-secret
  labels:
    {{- include "todo-service.labels" . | nindent 4 }}
  annotations:
    # Add annotation to indicate this should be managed externally in production
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    # Warning annotation for production use
    kubectl.kubernetes.io/last-applied-configuration: |
      # WARNING: This secret contains default values and should be replaced
      # with proper secret management in production environments.
      # Consider using External Secrets Operator, Sealed Secrets, or similar.
type: Opaque
data:
  {{- if or .Values.secrets.postgresConnectionString .Values.database.connectionString }}
  # Primary connection string approach (recommended)
  POSTGRES_CONNECTION_STRING: {{ include "todo-service.connectionString" . | b64enc | quote }}
  {{- else }}
  # Fallback individual fields approach
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  {{- end }}
---
{{- end }}

{{- if .Values.externalSecret.enabled }}
# External Secret configuration (requires External Secrets Operator)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "todo-service.fullname" . }}-external-secret
  labels:
    {{- include "todo-service.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.externalSecret.target.name | default (printf "%s-secret" (include "todo-service.fullname" .)) }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "todo-service.labels" . | nindent 10 }}
  data:
  {{- range .Values.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}